"""add_idx_user_sub_lookup

Revision ID: da0a81014466
Revises: ca16bab1a0cc
Create Date: 2026-06-29 05:02:16.143448
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da0a81014466'
down_revision: Union[str, None] = 'ca16bab1a0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_sub_lookup', 'user_subscriptions', ['segment_id', 'country_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_sub_lookup', table_name='user_subscriptions')
    # ### end Alembic commands ###
