#!/usr/bin/env bash
# Capture matching baseline metrics into docs/eval/.
# Run against a read-only DB URL (prod dump or SSH tunnel). Does not mutate data.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
STAMP="$(date +%F)"
OUT="docs/eval/report_baseline_v2_${STAMP}.md"
mkdir -p docs/eval
{
  echo "# Baseline v2 — ${STAMP}"
  echo
  echo "Generated by tools/run_baseline_v2.sh"
  echo
  echo "## Quarantine candidates snapshot"
  echo
  PYTHONPATH=. venv/bin/python tools/quarantine_candidates.py || echo "(quarantine tool skipped / empty)"
  echo
  echo "## Matching eval"
  echo
  PYTHONPATH=. venv/bin/python tools/eval_matching.py
} | tee "$OUT"
echo "Wrote $OUT"
echo "Next: export recall template with tools/export_recall_template.py"
